# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
selene = "kampfkarren/selene@0.27.1"
luau-lsp = "JohnnyMorganz/luau-lsp@1.32.3"
lune = "lune-org/lune@0.8.8"
wally = "upliftgames/wally@0.3.2"
stylua = "johnnymorganz/stylua@0.20.0"
rojo = "rojo-rbx/rojo@7.4.4"
wally-package-types = "johnnymorganz/wally-package-types@1.3.2"
